version: "3.7"

services:
  pgdev:
    ports:
      - "5432:5432"
    networks:
      backend:
        ipv4_address: 10.5.0.5
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    #     depends_on:
    #       mssql:
    #         condition: service_healthy
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: ts-node-docker
    expose:
      - "8000"
    ports:
      - "8000:8000"
    command: npm run dev
    networks:
      backend:
        ipv4_address: 10.5.0.6

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
